### PR TITLE
Some testing I made to improve (IMO) the cache-debugging appearance and behavior

### PR DESCRIPTION
**Pull request by mrbohnke**

### CODE REVIEW

**Comment by mrbohnke** [comment]
Please let me know what you think.

**Comment by mnshankar** [comment]
Thanks for the updates. It looks good :-)  Can you please update the documentation (readme) to reflect your changes? i.e. notes about the new params "?cache-info" and "?cache-clear"

**Comment by mrbohnke** [comment]
Right, totally forgot to do that!

**Comment by mrbohnke** [comment]
Did that and some other stuff, let me know what you think!

**Comment by mnshankar** [comment]
Thanks a lot..I appreciate you taking the time to make these updates 👍

**Comment by mrbohnke** [comment]
My pleasure.
Cheers.

**Pull request merged**
